### ISSUE TITLE
runservers error when loading styx

### ISSUE THREAD

**Issue by jbernardo95** [tidepool-org/tools#35]
I get an error when starting styx: `tp_styx:export:2: not valid in this context: "http":`

It is when it loads `styx_rules.json` to and ENV variable.

Do you any idea why is this happening ?

**Comment by jh-bate** [comment]
Hi @jbernardo95  - are you doing trying to run your setup as per [run-servers](https://github.com/tidepool-org/tools/blob/master/runservers) or [using vagrant](https://github.com/tidepool-org/tools#development-vm-using-vagrant)?

**Comment by jbernardo95** [comment]
I am trying to run it with `run-servers`, should I use vagrant instead ?

**Comment by jh-bate** [comment]
@jbernardo95 you should be fine with `run-servers` as that is what we mostly use. Any more details about the machine and setup your trying to run on at all? Is there more of a detailed stack trace??

**Comment by jbernardo95** [comment]
@jh-bate Here is a screenshot.

![Uploading Screen Shot 2015-07-08 at 11.49.03.png…](screenshot)

I am running it on a MacBook Pro with OS X Yosemite.

The error is kind of strange ...

**Comment by jh-bate** [comment]
Hi @jbernardo95  yeah it does look a bit strange :) 

There should be a ``server.log`` file created (you can see it mentioned in the console above) have a look in that file as it will probably shed some more light on the issue. 

Also from the log above there are multiple permission denied errors - the build scripts are pulling in the various deps and it looks like during that step is where those errors are happening. The woulds also need to be sorted out.

**Comment by jbernardo95** [comment]
@jh-bate I solved it !

It was me being a noobie, I didn't got those permission denied errors.

After running it in sudo mode, It ran with no problem.

Now I have the tidepool platform running locally right ?

**Comment by jh-bate** [comment]
@jbernardo95 well done!!

sorry been out of the loop for a couple of days so only read this now. Yeah you should be up and running now :)
