### ISSUE TITLE
Vagrant file sync breaks builds on Windows

### ISSUE THREAD

**Issue by mrinnetmaki** [tidepool-org/tools#42]
The approach where the whole tidepool directory is synced with the host machine seems to break things on Windows. See https://github.com/Sensotrend/sensotrend-tidepool/issues/3 for just one description, it seems most of the repos fail to build.

**Comment by mrinnetmaki** [comment]
Just disabling synced folders does not work either, straight away. When you initially checkout the tools repo with Windows, and then use the virtual machine to run scripts, there are some errors due to line endings (as they are now in CRLF format for Windows).

This could be fixed by marking the scripts as binary in .gitattributes, but that would make it somewhat less convenient to track the changes to the files.

Another possibility is to use @pazaan's repo https://github.com/pazaan/tidepool-vagrant, in which case the scripts are checked out with the linux machine and they work. At least my Windows machines still have issues with builds on synced folders, though.

We built another Vagrant installation that works with Windows, https://github.com/Sensotrend/sensotrend-tidepool. Should be good for just getting started with Tidepool on Windows, but does not have all the sources synced to the Windows host.

**Comment by jh-bate** [comment]
Hi @mrinnetmaki thanks for the heads up! OK if we link to your setup for a windows machine?

**Comment by mrinnetmaki** [comment]
Sure, by all means!

I can also do a pull request to Tidepool's tools repo, but didn't know what would be the best way, so it wouldn't spoil the setup for non-Windows users. Could perhaps be a different branch. Separate repository for just the Vagrant seemed to be a better option.

**Comment by mrinnetmaki** [comment]
Closing this as obsolete.
