### ISSUE TITLE
setup_vagrant.sh downloads wrong version of PhantomJS

### ISSUE THREAD

**Issue by auxlife** [tidepool-org/tools#70]
The script downloads version 1.9.8; but the latestget_current_tidepool_repos.sh complains it is the wrong version and then downloads 2.1.1.

**Comment by auxlife** [comment]
It also seems to be missing the steps to install nvm.

**Comment by cbwebdevelopment** [comment]
Thanks for reporting this issue.  

We will actually be deprecating our support of the vagrant development environment, and are now encouraging the use of our new Docker-based dev environment at /tidepool-org/development

I'll update the current documentation to reflect this, and will try to address these issues at some point in the next few weeks. 

In the meantime, if you have a PR to contribute for these fixes, that would be great.

**Comment by auxlife** [comment]
Thanks for the update; after spending DAYS trying to hunt down numerous issues with trying to build the stack w/ vagrant I ultimately gave up and setup the docker env.
